stof_doctrine_extensions:
  default_locale: fr_FR
  orm:
    default:
      timestampable: true


sylius_resource:
  resources:
    aropixel.stock_movement:
      driver: doctrine/orm
      classes:
        model: Aropixel\SyliusStockMovementPlugin\Entity\StockMovement
        interface: Aropixel\SyliusStockMovementPlugin\Entity\StockMovementInterface

sylius_ui:
  events:
    sylius.admin.product_variant.update.tab_inventory:
      blocks:
        stock.movement: '@AropixelSyliusStockMovementPlugin/Admin/stock_movement.html.twig'
    sylius.admin.product.update.tab_inventory:
      blocks:
        stock.movement: '@AropixelSyliusStockMovementPlugin/Admin/stock_movement.html.twig'
